### PR TITLE
Feature: Android support

### LINKED ISSUE #2: Android support
Implement Android support via https://github.com/airbnb/lottie-android

### PR DESCRIPTION
**Pull request by timbru31**
This is a ref to #2

### CODE REVIEW

**Comment by markosymphony** [comment]
Hey @timbru31, 

Please, can you merge this one into master as we need it for our project? :)

Thanks.

**Comment by timbru31** [comment]
Hi @markosymphony,

thanks for your interest! Sadly this is still WIP. Which feature set do you need? (e.g. loading from file or remote, JavScript bindings, hide timeout)  
I might be able to get an Android MVP ready next week

**Comment by markosymphony** [comment]
Hey @timbru31,

Thanks for the support. We need it for loading from file. Is that something that will work in this PR?
Also, we have some problem when we are building from `master` or this PR.

**Commands** : 
`meteor build ../build --server=node-polle.herokuapp.com  --mobile-settings settings.json
  meteor run ios-device --port 3003 --settings settings.json`

**ERROR**
```
While preparing Cordova project for platform Android:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Node version is : **10.12**

Do you have something on your mind what could be the problem ?
Thanks.

**Comment by timbru31** [comment]
> Thanks for the support. We need it for loading from file. Is that something that will work in this PR?
Partially. The animation is not automatically hidden (only on tap) and the animation is currently loaded from `www/lottie/data.json` (hardcoded).

> Also, we have some problem when we are building from master or this PR.
This should be fixed now, thanks for letting me know. I've also pushed v0.1.3 to npm. master and this PR branch are up to date, too

**Comment by markosymphony** [comment]
Thanks for the quick update @timbru31!

**Comment by timbru31** [comment]
@markosymphony - long time no see. I've finally merged the Android branch 🎉.
You can give the beta a try: cordova plugin add cordova-plugin-lottie-splashscreen@beta  
It might be a little bit rough around the edges, please report any issues you encounter.

**Pull request merged**
